<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>MSOfficeTemplateReport</Title>
    <Authors>Aleksandr Mokrinskiy</Authors>
    <Company>Vector-Best</Company>
    <Product>MSOfficeTemplateReport</Product>
    <Description>Создание отчетов по шаблонам Word и Excel</Description>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Version>1.0.12</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
  </ItemGroup>

</Project>
